num1= int(input("Enter first number:\n"))
num2= int(input("Enter second number:\n"))
print("The sum is:", num1+num2)
print("The subtract of two number is:", num1-num2)
print("The product is:", num1*num2)
print("The division is:", num1/num2)
print("The remainder is:", num1%num2)
print("The power of num1 and num2  is:", num1**num2)
print("the type of first number is:", type(num1))
print("the type of first number is:", type(num2))